### ISSUE TITLE
Caption not displaying

### ISSUE THREAD

**Issue by Perzec** [cconover/featured-image-caption#27]
Hey, I installed this plugin and the caption won't display on any featured image. Don't know what I'm doing wrong, or if it's the theme that's somehow incompatible.

Information: 

Version Information
Plugin: 0.6.2
WordPress: 4.2.2
PHP: 5.5.9-1ubuntu4.9

Theme
Name: MH Magazine
Version: 2.4.0

**Comment by Perzec** [comment]
Correction: it does not display when reading a post, but it does display in the slider on the front page. I do not want it to display in the slider on the front page though, but I do want it to display on the posts.

**Comment by cconover** [comment]
Ok, that makes sense. I think perhaps I need to add some controls on where the caption should appear. I'll add this to my to-do list!

**Comment by keithberry** [comment]
Hi there -- Mine aren't showing either. I use the Divi theme, it's activated, I have both boxes checked in the Featured Image Caption settings. I've inputted data, saved it and nothing! I even deleted the Featured Image and redid it from the start to see if that was the issue. Thoughts? Thanks.

**Comment by cconover** [comment]
I'm wondering if perhaps your theme doesn't support the method of automatic caption insertion used by the plugin.

I've [added a page](https://github.com/cconover/wp-featured-image-caption/wiki/%22Automatic-caption-insertion%22-isn't-working) on the wiki about automatic caption insertion not working. It may help you figure out the issue.
