### ISSUE TITLE
Not writing to loop?

### ISSUE THREAD

**Issue by AaronWinters916** [cconover/featured-image-caption#45]
Plug-in worked perfectly when first installed in May. Data is still showing in post/page dash metabox' but text has simply stopped showing on front end in the past 2 weeks. Was going to try to grab manually but I dont even see any reference to it in the SQL data. 

Site is child theme of 2014. Everything is up-to-date. Have read all other documentation here, but no luck.

**Comment by cconover** [comment]
Hmmm. The caption data for each post should be in the `postmeta` table of your database with the name `_cc_featured_image_caption`.

Which version of the plugin are you using?

**Comment by AaronWinters916** [comment]
The newest one you pushed (0.8.1 I believe).

I subbed the first half of dev on this site and the database is a train wreck. I looked for that name but didn’t see it. Will look again.

**Comment by cconover** [comment]
Did the issue start with the latest version of the plugin?

**Comment by AaronWinters916** [comment]
Issue began prior to 081, yes. Whatever version was current in early May. I actually hadn’t touched the site in a few weeks but client noticed the captions were gone.

The field is there in DB, which makes better sense. :-) Still not being called in WP though. 

I see mention in commented code to include in The Loop. I didn’t originally move anything manually. Does this need to be done in the newer versions?

**Comment by cconover** [comment]
I added a setting in 0.8.2 to restrict the automatically appended caption to only be performed when viewing a single post, but this is off by default. You may want to check the plugin settings to make sure of that. That's based on my understanding that you're not seeing the caption when viewing post listings on the blog or archive pages, correct?

**Comment by AaronWinters916** [comment]
I knew about the update and made sure that wasn’t selected.

Im not seeing them on either pages or posts.

**Comment by cconover** [comment]
Did you change or update your site's theme?

**Comment by AaronWinters916** [comment]
Its a custom child theme, but I haven’t done anything to the template.php since before the plug-in was originally added. (Im the only one with admin access too.) 

I have already double-checked that display:none isn’t zapping it either, just in case a selector got changed.

**Comment by cconover** [comment]
Can you provide a link to show an example of what's happening?

**Comment by AaronWinters916** [comment]
http://www.zoescruises.com/team/zoe-mccrea/ <http://www.zoescruises.com/team/zoe-mccrea/>

Right hand side between banner and text area should be the featured caption, styled like the other ones within the content block.

Should be writing on line 155 or 159.

As you can see here, area is collapsed, and is not being written to DOM, etc. “Inaugural…” caption text is also entered on the dash end.

**Comment by cconover** [comment]
I'm seeing caption text where you've referred to, did you manage to resolve the issue or am I looking in the wrong place?

**Comment by AaronWinters916** [comment]
Just double-checked and no, its still not there. Marked the location in screenshot here.

There are other captions elsewhere on the page coming from Advanced Custom Fields, just not the one for the featured banner that your plug-in should be showing.

In the second screenshot here, you’ll see that the dash input is holding the info and its being saved to the DB but not being written to the page.

**Comment by cconover** [comment]
There aren't any screenshots, can you post the images online somewhere and link to them?

**Comment by AaronWinters916** [comment]
https://www.dropbox.com/s/hej9s5r8iu8504v/ccScreens.zip?dl=0

**Comment by AaronWinters916** [comment]
Had a friend take a look and have it figured out: Injected PHP line goes to parent theme header.php, not the custom child theme's header. Once I moved the line forward the problem was resolved.

**Comment by cconover** [comment]
Excellent! Thanks for reporting back with your solution.
