### ISSUE TITLE
Does not show up in edit mode

### ISSUE THREAD

**Issue by heidi8588** [cconover/featured-image-caption#64]
This plug in does not show up after I installed it.
![screen shot 2016-12-29 at 11 23 32 am](https://cloud.githubusercontent.com/assets/24829882/21549484/0da2d214-cdb8-11e6-9847-3ac5b0bd6d45.png)

Version Information
Plugin: 0.8.6
WordPress: 4.6.1
PHP: 5.5.9-1ubuntu4.20

Theme
Name: Themify Ultra
Version: 1.6.3

**Comment by cconover** [comment]
Is this still an issue? The plugin now requires PHP >= `5.6.0`.

**Comment by cconover** [comment]
Since there's been no response I'm going to close the issue.
