### ISSUE TITLE
Paragraph

### ISSUE THREAD

**Issue by ReinerKnudsen** [cconover/featured-image-caption#65]
Is there a way to avoid the automatic paragraph before the result of the shortcode? When I enter
`Picture: [ccfic source-link]` as shortcode I expect the following output:

Picture: _sourcelink_

but it always comes out as

Picture:
_sourcelink_

Any idea?
Thanks.

**Comment by cconover** [comment]
Have you taken a look at the [documentation for the flags available for the shortcode](https://github.com/cconover/featured-image-caption/wiki/Shortcode)? I think you might be able to do what you're looking for.
