### ISSUE TITLE
I would like to put a link into the thumbnail image

### ISSUE THREAD

**Issue by HowardLeeHarkness** [cconover/featured-image-caption#66]
This plugin does *almost* everything I want.

Feature request: I would like to have a link that would be inserted into the thumbnail, so that clicking on the thumbnail image would take me directly to that link (not the permalink for the post, but another site). There would be a different URL for each thumbnail image.

Alternatively, perhaps you could provide a function that just returned the URL field under Source Attribution, so I could modify my child theme to use that as a link. Or, if there is already such a function, you could just show me how to use it in the following code excerpt:

    if (get_the_post_thumbnail()) {
        echo '<div class="masonry-image">';
        the_post_thumbnail('shop_catalog');
        echo '</div>';
    }

Details on plugin/theme:
Version Information
Plugin: 0.8.6
WordPress: 4.7.3
PHP: 5.4.45

Theme
Name: vice Child (parent theme is Vice, I will probably try some others because this one does not appear to be sufficiently responsive)
Version: 1.0.8.1492300688

**Comment by cconover** [comment]
You might be able to get the result you're looking for using the [plugin function `cc_featured_image_caption()`](https://github.com/cconover/featured-image-caption/wiki/Function-Reference), by passing the `html=false` argument and getting back the array of caption data, which you could then render however you'd like.

**Comment by HowardLeeHarkness** [comment]
Thank you for your response. I was able to do what I wanted using a plugin called External Permalinks Redux
