### ISSUE TITLE
Fatal error: Class not found in featured-image-caption.php on line 46

### ISSUE THREAD

**Issue by Viva57** [cconover/featured-image-caption#68]
Two of my websites recently developed an issue without any trigger that I can pin-point. Wordpress has not been updated on the day the issue first occurred. The result is 

Fatal error: Class 'cconover\FeaturedImageCaption\Bootstrap' not found in /usr/www/users/mywebsite/wp-content/plugins/featured-image-caption/featured-image-caption.php on line 46

In the meantime I was able to get the site back up by disabling the plugin as a temporary measure.

My Site info: SQL 97 • PHPv 5.6.40-0+deb8u1  • Wordpress Version 5.0.3

**Comment by cconover** [comment]
This was fixed by #67, included in version 0.8.7. Thanks @todeveni for the fix! Sorry it took me so long to finally accept it 🙃
